# FORMATTER NOTE: The versions of ufmt, black and usort should be consistent everywhere
# (pre-commit, environment.yml, requirements.txt, pyproject.toml, ...)

repos:
- repo: https://github.com/jsh9/pydoclint
  rev: 0.2.1
  hooks:
    - id: pydoclint
      args: [--config=pydoclint.cfg]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.6
  hooks:
  - id: ruff
    name: "ruff"
    args: [--config=ruff.cfg]
  - id: ruff-format
- repo: https://github.com/crate-ci/typos
  rev: v1.16.23
  hooks:
    - id: typos
      args: [] # empty args to avoid typos automatically correcting the typos

