name: baybe
channels:
- conda-forge
dependencies:
- python==3.8.6
- flake8==4.0.1
- matplotlib==3.5.2
- mordred==1.2.0
- openpyxl==3.0.9
- pre-commit==2.19.0
- pylint==2.13.9
- pip==22.1.2
- pandas==1.4.2
- pydantic==1.9.1
- pytorch==1.11.0
- rdkit==2022.3.4
- scikit-learn==1.1.1
- seaborn==0.11.2
- streamlit==1.10.0
- pip:
  # temporarily install botorch and gpytorch via pip until the linear_operator recipe
  # has been merged into conda-forge, which resolves the current dependency issues
  - botorch==0.7.0
  - gpytorch==1.9.0
  - ufmt==1.3.2
