name: baybe
channels:
- conda-forge
dependencies:
- python==3.8.6
- botorch==0.6.4
- flake8==4.0.1
- pre-commit==2.19.0
- pylint==2.13.9
- pip==22.1.2
- pandas==1.4.2
- pip:
  - ufmt==1.3.2
  - scikit-learn==1.1.1
