# DEV TOOLS NOTE: The versions of all dev tools should be consistent everywhere
# (pre-commit, environment.yml, requirements.txt, pyproject.toml, ...)

name: baybe
channels:
- conda-forge
dependencies:
- python==3.8.6
- attrs==22.2.0
- black==22.3.0  # see DEV TOOLS NOTE
- botorch==0.8.1
- cattrs==22.2.0
- flake8==4.0.1  # see DEV TOOLS NOTE
- fsspec==2022.10.0
- funcy==1.17
- gpytorch==1.9.1
- matplotlib==3.5.2
- mordred==1.2.0
- mypy==1.2.0
- numpy==1.23.4
- openpyxl==3.0.9
- opentelemetry-sdk==1.16.0
- opentelemetry-exporter-otlp==1.16.0
- pre-commit==2.19.0  # see DEV TOOLS NOTE
- pylint==2.17.2  # see DEV TOOLS NOTE
- pip==22.1.2
- pandas==1.4.2
- plotly==5.10.0
- pydantic==1.9.1
- pytest==7.2.0
- pytorch==1.11.0
- rdkit==2022.3.4
- scikit-learn==1.1.1
- scikit-learn-extra==0.2.0
- scipy==1.9.3
- seaborn==0.11.2
- setuptools-scm==7.1.0
- streamlit==1.20.0
- typing_extensions==4.5.0  # Can be removed with pydantic or once this gets resolved: https://github.com/pydantic/pydantic/issues/545#issuecomment-1559115237
- pip:
  # Temporarily install ngboost via pip to resolve scikit-learn dependency
  # The conda-forge version requires >=0.21, <=0.24 but pip only needs >=0.21
  - ngboost==0.3.12
  - opentelemetry-propagator-aws-xray==1.0.0
  - opentelemetry-sdk-extension-aws==2.0.0
  - ufmt==1.3.2  # see DEV TOOLS NOTE
  - usort==1.0.2  # see DEV TOOLS NOTE
