# The following are options that are used for pydoclint
[tool.pydoclint]
style = "google" # Use google docstring style 
arg-type-hints-in-docstring = false # We do not have the type hints in the docstrings
check-return-types = false #  We do not have the return types in the docstrings
exclude = "validat" # Skip files that are only used for validation