[project]
name = "BayBE"
description = "Bayesian Back End for Design of Experiments"
authors = [
    {name = "Martin Fitzner", email = "martin.fitzner@merckgroup.com"},
    {name = "Adrian Šošić", email = "adrian.sosic@merckgroup.com"},
]
requires-python =">=3.8"
dependencies = [
    "botorch>=0.6.4",
]

[project.optional-dependencies]
dev = [
    "flake8>=4.0.1",
    "pre-commit>=2.19.0",
    "pylint>=2.13.9",
    "ufmt>=1.3.2",
]

[tool.black]
line-length = 88