[project]
name = "BayBE"
description = "Bayesian Back End for Design of Experiments"
authors = [
    {name = "Martin Fitzner", email = "martin.fitzner@merckgroup.com"},
    {name = "Adrian Šošić", email = "adrian.sosic@merckgroup.com"},
]
requires-python =">=3.8"
dependencies = [
    "botorch>=0.6.4",
]

[project.optional-dependencies]
dev = [
    "flake8>=4.0.1",
    "pre-commit>=2.19.0",
    "pylint>=2.13.9",
    "ufmt>=1.3.2",
]

[tool.black]
line-length = 88

[tool.pylint.TYPECHECK]
# List of members which are set dynamically and missed by pylint inference
# system, and so shouldn't trigger E1101 when accessed. Python regular
# expressions are accepted.
generated-members = "torch.*"

[tool.pylint.'MESSAGES CONTROL']
disable = [
	"fixme",  # fixme hints should be allowed
	"wrong-import-order",  # handled by ufmt
	"duplicate-code",  # duplicate code happens eg in similar debug scripts
	"too-many-instance-attributes",  # BayBE class has quite a few members
    "too-many-branches",  # Can maybe be optimized later
	]